### ISSUE TITLE
Allow serialize to handle custom expiration time

### ISSUE THREAD

**Issue by TommyTraddles** [Riftland/simple-stateless-auth-library#1]
Enable a third argumento in the `serialize` function to handle custom `expiration time`

**Comment by Riftland** [comment]
Now `serialize` can receive a third param, an object that contains `type` and `value` properties:
-> `type`: It represents the time unit that `value` contains. It's a string and It can be one of these values: d, h, m, s, ms
-> `value`: numeric representation of time regarding its `type`

Example:
```js
const expOptions = {
    value: 10,
    type: 'd',
}

serialize(res, payload, expOptions) 
// the cookie will last ten days. In case It was `undefined`, the fallback is 300000ms (5mins)
```
